Repository FIS2425/staff-svc, pull requests merged in 2024-11, with the labels that each got.

#12 feat: delete doctor
  openapi.yaml
  src/api.js
  src/controllers/doctorController.js
  src/routes/doctorRoute.js
Labels: 😎 size/m

#10 feat: update speciality of a doctor
  openapi.yaml
  src/controllers/doctorController.js
  src/routes/doctorRoute.js
Labels: size/s

#24 refactor: logger updated
  openapi.yaml
  src/controllers/doctorController.js
  src/routes/doctorRoute.js
Labels: 😎 size/m

#27 Chore: Update Openapi of Api Gateway
  .github/workflows/trigger-api-sync.yml
Labels: 🚀 CI/CD, size/s

#28 test: Add unit test for staff controller
  tests/unit/controllers/dummy
  tests/unit/controllers/staff.test.js
Labels: 🧪 Tests, size/s

#33 Feat: Integration with auth service
  .env.example
  package-lock.json
  package.json
  src/controllers/doctorController.js
  src/middleware/verifyAdmin.js
  src/middleware/verifyAuth.js
  src/routes/doctorRoute.js
  src/utils/validation.js
Labels: 📦 Dependencies, 👀 Feature Requested, ⚙️ Configuration, 😎 size/m, 🚀 Feature

#35 Fix: Id attributes from doctor model
  src/controllers/doctorController.js
  src/routes/doctorRoute.js
  src/schemas/Doctor.js
  tests/unit/controllers/staff.test.js
Labels: 🧪 Tests, 🕵🏻 Fix, size/s

#36 Test: testing schema
  src/schemas/Doctor.js
  tests/unit/schemas/doctor.test.js
  tests/unit/schemas/dummy
Labels: 🧪 Tests, 😎 size/m

#41 feat: create swagger
  openapi.yaml
Labels: size/xs

#43 feat: Implemented get logged doctor
  openapi.yaml
  src/controllers/doctorController.js
  src/routes/doctorRoute.js
Labels: size/s
