Repository FIS2425/staff-svc, pull requests merged in 2025-01, with the labels that each got.

#93 Feat: add ids to populator
  populators/runPopulator.js
Labels: 👀 Feature Requested, size/xs

#96 Chore: mongodb staff renamed
  kubernetes/mongodb-deployment.yaml
  kubernetes/mongodb-service.yaml
Labels: size/s

#97 Release 1.0.4
  kubernetes/mongodb-deployment.yaml
  kubernetes/mongodb-service.yaml
  openapi.yaml
  populators/runPopulator.js
Labels: size/s

#101 hotfix: populator id fixed
  populators/runPopulator.js
Labels: size/xs

#103 Chore: delete env var not used in kubernetes files
  .env.example
  .github/workflows/docker-deploy.yml
  kubernetes/staff-svc-deployment.yaml
  package-lock.json
  package.json
  populators/runPopulator.js
Labels: 📦 Dependencies, ⚙️ Configuration, 🚀 CI/CD, size/s

#106 Feat: cherry pick
  src/api.js
  src/config/logger.js
  src/utils/kafkaTransport.js
Labels: size/s

#107 Feat: feature toggle added
  .env.example
  kubernetes/staff-svc-deployment.yaml
  populators/runPopulator.js
  src/controllers/doctorController.js
  tests/unit/controllers/staff.test.js
Labels: 👀 Feature Requested, 🧪 Tests, ⚙️ Configuration, size/s

#111 chore: changed loadbalancer to clusterip
  kubernetes/staff-svc-service.yaml
Labels: size/xs

#110 Feat: add workflow to deploy in aks
  .github/workflows/deploy-aks.yaml
  package-lock.json
  package.json
Labels: 📦 Dependencies, 🚀 CI/CD, size/s

#113 Fix(staff): workflow to deploy
  .github/workflows/deploy-aks.yaml
  package-lock.json
  package.json
Labels: 📦 Dependencies, 🚀 CI/CD, size/xs

#114 fix(staff): docker deploy workflow
  .github/workflows/docker-deploy.yml
Labels: 🚀 CI/CD, size/xs

#112 Release 1.0.7
  .env.example
  .github/workflows/deploy-aks.yaml
  .github/workflows/docker-deploy.yml
  kubernetes/staff-svc-deployment.yaml
  kubernetes/staff-svc-service.yaml
  package-lock.json
  package.json
  populators/runPopulator.js
  src/api.js
  src/config/logger.js
  src/controllers/doctorController.js
  src/utils/kafkaTransport.js
  tests/unit/controllers/staff.test.js
Labels: 📦 Dependencies, 🧪 Tests, ⚙️ Configuration, 😎 size/m, 🚀 CI/CD

#116 hotfix(staff): kafka logger fixed
  src/config/logger.js
  src/utils/kafkaTransport.js
Labels: size/xs

#117 Feat/change err status register
  .github/workflows/deploy-aks.yaml
  src/config/logger.js
  src/controllers/doctorController.js
  src/utils/kafkaTransport.js
Labels: 🚀 CI/CD, size/s

#118 Release 1.0.8
  src/controllers/doctorController.js
Labels: size/s

#120 Hotfix: feature toggle
  src/controllers/doctorController.js
  tests/unit/controllers/staff.test.js
Labels: 🧪 Tests, size/s
